parameters:
#    lpas_shop.example.class: Lpas\ShopBundle\Example

services:
#    lpas_shop.example:
#        class: %lpas_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
