parameters:
#    lpas_common.example.class: Lpas\CommonBundle\Example

services:
    lpas_main.menu_builder:
        class: Lpas\CommonBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    lpas_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: lpas_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    lpas_main.menu.shop:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: lpas_main.menu_builder
        factory_method: createShopMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: shop } # The alias is what is used to retrieve the menu